name: MarkdownQuickLook
options:
  bundleIdPrefix: com.markdownquicklook
  deploymentTarget:
    macOS: "11.0"
targets:
  MarkdownQuickLook:
    type: application
    platform: macOS
    sources: [Sources/MarkdownQuickLook]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.markdownquicklook.app
      INFOPLIST_FILE: Sources/MarkdownQuickLook/Info.plist
      INFOPLIST_KEY_NSMainStoryboardFile: ""
      CODE_SIGN_ENTITLEMENTS: Sources/MarkdownQuickLook/MarkdownQuickLook.entitlements
      ENABLE_PREVIEWS: NO
      MARKETING_VERSION: ${MARKETING_VERSION}
      CURRENT_PROJECT_VERSION: ${CURRENT_PROJECT_VERSION}
    preBuildScripts:
      - name: Increment Build Number
        script: |
          sh "$SRCROOT/scripts/increment_version.sh"
        runOnlyWhenInstalling: false
    postBuildScripts:
      - name: Apply Build Number
        script: |
          sh "$SRCROOT/scripts/apply_version.sh"
        runOnlyWhenInstalling: false
    dependencies:
      - target: MarkdownPreview
        embed: true

  MarkdownPreview:
    type: app-extension
    platform: macOS
    sources:
      - Sources/MarkdownPreview
      - path: web-renderer/dist
        name: WebRenderer
        type: folder
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.markdownquicklook.app.MarkdownPreview
      INFOPLIST_FILE: Sources/MarkdownPreview/Info.plist
      CODE_SIGN_ENTITLEMENTS: Sources/MarkdownPreview/MarkdownPreview.entitlements
      SKIP_INSTALL: YES
      MARKETING_VERSION: ${MARKETING_VERSION}
      CURRENT_PROJECT_VERSION: ${CURRENT_PROJECT_VERSION}
    postBuildScripts:
      - name: Apply Build Number
        script: |
          sh "$SRCROOT/scripts/apply_version.sh"
        runOnlyWhenInstalling: false
    dependencies:
      - sdk: QuickLookUI.framework
