name: MarkdownPreviewEnhanced
options:
  bundleIdPrefix: com.xykong
  deploymentTarget:
    macOS: "11.0"
targets:
  Markdown:
    type: application
    platform: macOS
    sources: 
      - Sources/Markdown
      - path: web-renderer/dist
        name: WebRenderer
        type: folder
    settings:
      PRODUCT_NAME: "Markdown Preview Enhanced"
      PRODUCT_BUNDLE_IDENTIFIER: com.xykong.Markdown
      INFOPLIST_FILE: Sources/Markdown/Info.plist
      INFOPLIST_KEY_NSMainStoryboardFile: ""
      CODE_SIGN_ENTITLEMENTS: Sources/Markdown/Markdown.entitlements
      ENABLE_PREVIEWS: NO
      MARKETING_VERSION: ${MARKETING_VERSION}
      CURRENT_PROJECT_VERSION: ${CURRENT_PROJECT_VERSION}
    preBuildScripts:
      - name: Increment Build Number
        script: |
          sh "$SRCROOT/scripts/increment_version.sh"
        runOnlyWhenInstalling: false
    postBuildScripts:
      - name: Apply Build Number
        script: |
          sh "$SRCROOT/scripts/apply_version.sh"
        runOnlyWhenInstalling: false
    dependencies:
      - target: MarkdownPreview
        embed: true

  MarkdownPreview:
    type: app-extension
    platform: macOS
    sources:
      - Sources/MarkdownPreview
      - path: web-renderer/dist
        name: WebRenderer
        type: folder
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.xykong.Markdown.QuickLook
      INFOPLIST_FILE: Sources/MarkdownPreview/Info.plist
      CODE_SIGN_ENTITLEMENTS: Sources/MarkdownPreview/MarkdownPreview.entitlements
      SKIP_INSTALL: YES
      MARKETING_VERSION: ${MARKETING_VERSION}
      CURRENT_PROJECT_VERSION: ${CURRENT_PROJECT_VERSION}
    postBuildScripts:
      - name: Apply Build Number
        script: |
          sh "$SRCROOT/scripts/apply_version.sh"
        runOnlyWhenInstalling: false
    dependencies:
      - sdk: QuickLookUI.framework

  MarkdownTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/MarkdownTests
    dependencies:
      - target: Markdown
