name: MarkdownQuickLook
options:
  bundleIdPrefix: com.markdownquicklook
  deploymentTarget:
    macOS: "11.0"
targets:
  MarkdownQuickLook:
    type: application
    platform: macOS
    sources: [Sources/MarkdownQuickLook]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.markdownquicklook.app
      INFOPLIST_FILE: Sources/MarkdownQuickLook/Info.plist
      INFOPLIST_KEY_NSMainStoryboardFile: ""
      CODE_SIGN_ENTITLEMENTS: Sources/MarkdownQuickLook/MarkdownQuickLook.entitlements
      ENABLE_PREVIEWS: NO
    dependencies:
      - target: MarkdownPreview
        embed: true

  MarkdownPreview:
    type: app-extension
    platform: macOS
    sources:
      - Sources/MarkdownPreview
      - path: web-renderer/dist
        name: WebRenderer
        type: folder
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.markdownquicklook.app.MarkdownPreview
      INFOPLIST_FILE: Sources/MarkdownPreview/Info.plist
      CODE_SIGN_ENTITLEMENTS: Sources/MarkdownPreview/MarkdownPreview.entitlements
      SKIP_INSTALL: YES
    dependencies:
      - sdk: QuickLookUI.framework
