name: FluxMarkdown
options:
  bundleIdPrefix: com.xykong
  deploymentTarget:
    macOS: "11.0"
packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    exactVersion: 2.8.1
targets:
  Markdown:
    type: application
    platform: macOS
    sources: 
      - Sources/Markdown
      - Sources/Shared
      - path: web-renderer/dist
        name: WebRenderer
        type: folder
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      PRODUCT_NAME: "FluxMarkdown"
      PRODUCT_BUNDLE_IDENTIFIER: com.xykong.Markdown
      INFOPLIST_FILE: Sources/Markdown/Info.plist
      INFOPLIST_KEY_NSMainStoryboardFile: ""
      CODE_SIGN_ENTITLEMENTS: Sources/Markdown/Markdown.entitlements
      ENABLE_PREVIEWS: NO
      MARKETING_VERSION: ${MARKETING_VERSION}
      CURRENT_PROJECT_VERSION: ${CURRENT_PROJECT_VERSION}
    dependencies:
      - target: MarkdownPreview
        embed: true
      - package: Sparkle
        product: Sparkle

  MarkdownPreview:
    type: app-extension
    platform: macOS
    sources:
      - Sources/MarkdownPreview
      - Sources/Shared
      - path: web-renderer/dist
        name: WebRenderer
        type: folder
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.xykong.Markdown.QuickLook
      INFOPLIST_FILE: Sources/MarkdownPreview/Info.plist
      CODE_SIGN_ENTITLEMENTS: Sources/MarkdownPreview/MarkdownPreview.entitlements
      SKIP_INSTALL: YES
      MARKETING_VERSION: ${MARKETING_VERSION}
      CURRENT_PROJECT_VERSION: ${CURRENT_PROJECT_VERSION}
    dependencies:
      - sdk: QuickLookUI.framework

  MarkdownTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/MarkdownTests
      - Sources/Markdown/ResourceLoader.swift
      - Sources/MarkdownPreview
      - Sources/Shared
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.xykong.Markdown.Tests

schemes:
  Markdown:
    build:
      targets:
        Markdown: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: MarkdownTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
